export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';


